<a href="https://colab.research.google.com/github/braiden-goodey/TEDA1041/blob/main/Module_3_Projectipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [ ]:
response = requests.get('https://btech-data-analytics.github.io/bridgerland-technical-college/bookstore.html').text

In [ ]:
soup = BeautifulSoup(response, 'html.parser')

In [ ]:
ISBN =[]
Title = []
Author = []
Language = []
Pages = []
Topic = []
Price = []

for employee in soup.find ('table').find_all('tr', class_='book'):
  ISBN.append (employee.find_all('td')[0].text)
  Title.append (employee.find_all('td')[1].text)
  Author.append (employee.find_all('td')[2].text)
  Language.append (employee.find_all('td')[3].text)
  Pages.append (employee.find_all('td')[4].text)
  Topic.append (employee.find_all('td')[5].text)
  Price.append (employee.find_all('td')[6].text)

In [ ]:
df = pd.DataFrame({
    'ISBN': ISBN,
    'Title': Title,
    'Author': Author,
    'Language': Language,
    'Pages': Pages,
    'Topic': Topic,
    'Price': Price
})
df.head()

,ISBN,Title,Author,Language,Pages,Topic,Price
0,978-1234567890,Whiskers of Wisdom: Tales from Feline Philosop...,Penelope Wainwright,English,256,Cats,$19.99
1,978-2345678901,Purrfectly Pawesome: A Cat's Life,Jasper Sterling,English,192,Cats,$15.99
2,978-3456789012,Cat Tales: Adventures in Whiskerland,Penelope Wainwright,English,320,Cats,$21.99
3,978-4567890123,The Enigmatic Paws: Mysteries of Meowville,Maximilian Thorne,English,288,Cats,$17.99
4,978-5678901234,Cats in Wonderland,Isadora Harrington,English,224,Cats,$16.99

In [ ]:
#Q1
df['Author'].value_counts()

Author
Penelope Wainwright    4
Jasper Sterling        2
Benjamin Barkley       2
Maximilian Thorne      1
Celeste Nightshade     1
Isadora Harrington     1
Seraphina Montague     1
Sophie Shepherd        1
Oliver Obedience       1
Ruby Ruffington        1
Name: count, dtype: int64

In [ ]:
#Q2
df['Topic'].value_counts()

Topic
Cats    10
Dogs     5
Name: count, dtype: int64

In [ ]:
#Q3
df['Price'] = df['Price'].str.replace('$', '', regex=False).astype(float)
df.groupby('Topic')['Price'].mean()

Topic
Cats    17.79
Dogs    26.59
Name: Price, dtype: float64

In [ ]:
#Q4
df['Pages'] = df['Pages'].astype(int)
df.groupby('Topic')['Pages'].mean()

Topic
Cats    238.4
Dogs    256.0
Name: Pages, dtype: float64